services:
  affichage:
    build: .
    volumes:
      - affichage_uploads:/app/static/uploads
      - affichage_icons:/app/static/icons
      - affichage_videos:/app/static/videos
      - affichage_db:/app/data
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
    restart: unless-stopped

volumes:
  affichage_uploads:
  affichage_icons:
  affichage_videos:
  affichage_db:
